[package]
name = "saha_parser"
version = "0.1.0"
authors = ["Otto Rask"]
edition = "2018"

[dependencies]
saha_lib = { path = "../lib" }
saha_tokenizer = { path = "../tokenizer" }
noisy_float = "0.1.*"